# URL de connexion à PostgreSQL
flyway.url=jdbc:postgresql://localhost:5432/cinephoria
flyway.user=postgres
flyway.password=Piantek09@

# Schéma à migrer
flyway.schemas=public

# Dossier des migrations SQL
flyway.locations=filesystem:./migrations

# Baseline pour DB existante
flyway.baselineOnMigrate=true
flyway.baselineVersion=1
flyway.baselineDescription=Initial version
